version: '3.8'

services:
  app:
    build: .
    ports:
      - "${APP_HOST_PORT}:${APP_CONTAINER_PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npx prisma db push && npm run start:dev"
    environment:
      - DATABASE_URL=${DOCKER_DATABASE_URL}
      - APP_PORT=${APP_CONTAINER_PORT}
      - REDIS_URL=${REDIS_HOST_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - '${REDIS_HOST_PORT}:6379'

volumes:
  pgdata:
